org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=false
org.gradle.debug=false

neogradle.subsystems.parchment.minecraftVersion=1.21
neogradle.subsystems.parchment.mappingsVersion=2024.07.07

minecraft_version=1.21
minecraft_version_range=[1.21,1.22)
neo_version=21.0.78-beta
neo_version_range=[21.0.0-beta,)
loader_version_range=[4,)

mod_id=luckytntmod
mod_name=Lucky TNT Mod
mod_license=All Rights Reserved
mod_version=6.1
mod_group_id=luckytntmod
mod_authors=Fleshcrafter, SlimingHD
mod_description=Lucky TNT adds tons of new TNT to destroy your world with!
